// -----------------------------------------------------------------------
// <autogenerated>
//    This code was generated from a template.
// 
//    Changes to this file may cause incorrect behaviour and will be lost
//    if the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------
namespace BlueDog.DataProvider
{
    [System.CodeDom.Compiler.GeneratedCode("PCLMock", "5.0.3.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class DataProviderMock : global::PCLMock.MockBase<global::BlueDog.DataProvider.IDataProvider>, global::BlueDog.DataProvider.IDataProvider
    {
        public DataProviderMock(global::PCLMock.MockBehavior behavior = global::PCLMock.MockBehavior.Strict): base (behavior)
        {
            ConfigureBehaviorGenerated();
            ConfigureBehavior();
            if ((behavior) == (global::PCLMock.MockBehavior.Loose))
            {
                ConfigureLooseBehaviorGenerated();
                ConfigureLooseBehavior();
            }
        }

        private void ConfigureBehaviorGenerated()
        {
        }

        private void ConfigureLooseBehaviorGenerated()
        {
        }

        partial void ConfigureBehavior();
        partial void ConfigureLooseBehavior();
        public void Initialize(global::BlueDog.Models.ServerConfiguration configuration)
        {
            this.Apply(x => x.Initialize(configuration));
        }

        public global::System.Threading.Tasks.Task<global::BlueDog.BlueDogResult> SaveUser(global::BlueDog.Models.User user)
        {
            return this.Apply(x => x.SaveUser(user));
        }

        public global::System.Threading.Tasks.Task<global::BlueDog.Models.User> GetUserByEmail(System.String email)
        {
            return this.Apply(x => x.GetUserByEmail(email));
        }

        public global::System.Threading.Tasks.Task<global::BlueDog.Models.User> GetUserById(System.String id)
        {
            return this.Apply(x => x.GetUserById(id));
        }

        public global::System.Threading.Tasks.Task<global::BlueDog.Models.User> GetUserByEmailValidation(System.String validation)
        {
            return this.Apply(x => x.GetUserByEmailValidation(validation));
        }
    }
}
